/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.snakes.SnakeGame;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Toolkit;

/**
 *
 * @author Luis
 */
public class TelaJogo extends javax.swing.JFrame {
    private PaneJogo canvas;
    private SnakeGame game;
    
    /**
     * Creates new form TelaJogo
     */
    public TelaJogo(SnakeGame game) {
        initComponents();
        
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);
        
        this.game = game;
        canvas = new PaneJogo(game);
        paneJogo.setPreferredSize(canvas.renderSize);
        paneJogo.setLayout(new GridLayout());

        canvas.setIgnoreRepaint(false);

        paneJogo.add(canvas);

        this.pack();
        this.setResizable(false);
        this.setVisible(true);

        canvas.requestFocus();
    }
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneJogo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Snake | Jogo");

        paneJogo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout paneJogoLayout = new javax.swing.GroupLayout(paneJogo);
        paneJogo.setLayout(paneJogoLayout);
        paneJogoLayout.setHorizontalGroup(
            paneJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        paneJogoLayout.setVerticalGroup(
            paneJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneJogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneJogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel paneJogo;
    // End of variables declaration//GEN-END:variables
    
    public PaneJogo getCanvas() {
        return this.canvas;
    }
}
