/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author Luis
 */
public class TelaAjuda extends javax.swing.JFrame {

    /**
     * Creates new form TelaAjuda
     */
    public TelaAjuda() {
        initComponents();
                
        //Centraliza a tela
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);
                
        //Centraliza os textos
        SimpleAttributeSet center = new SimpleAttributeSet();
        StyleConstants.setAlignment(center, StyleConstants.ALIGN_CENTER);
        
        StyledDocument doc = txtAjuda.getStyledDocument();
        doc.setParagraphAttributes(0, doc.getLength(), center, false);
        
        StyledDocument doc2 = txtAjuda2.getStyledDocument();
        doc2.setParagraphAttributes(0, doc2.getLength(), center, false);
        
        StyledDocument doc3 = txtAjuda3.getStyledDocument();
        doc3.setParagraphAttributes(0, doc2.getLength(), center, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneConfig = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAjuda2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAjuda = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAjuda3 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        paneConfig.setBackground(new java.awt.Color(255, 255, 255));
        paneConfig.setMaximumSize(new java.awt.Dimension(400, 450));
        paneConfig.setMinimumSize(new java.awt.Dimension(400, 450));
        paneConfig.setName(""); // NOI18N
        paneConfig.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 209, 30));
        jLabel3.setText("Tamanho Inicial dos Bots");
        paneConfig.add(jLabel3);
        jLabel3.setBounds(130, 10, 250, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 209, 30));
        jLabel5.setText("Tempo Limite para Movimento");
        paneConfig.add(jLabel5);
        jLabel5.setBounds(120, 130, 300, 40);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);

        txtAjuda2.setEditable(false);
        txtAjuda2.setBackground(new java.awt.Color(255, 255, 255));
        txtAjuda2.setBorder(null);
        txtAjuda2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAjuda2.setForeground(new java.awt.Color(0, 209, 30));
        txtAjuda2.setText("O tempo (em segundos) que cada bot (cobra) terá para executar seu algoritmo e decidir seu caminho, essa medida afeta principalmente os algoritmos mais complexos que precisam de tempo para tomar uma decisão.\nEsse campo suporta valores decimais.");
        jScrollPane2.setViewportView(txtAjuda2);

        paneConfig.add(jScrollPane2);
        jScrollPane2.setBounds(10, 170, 480, 110);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(null);

        txtAjuda.setEditable(false);
        txtAjuda.setBackground(new java.awt.Color(255, 255, 255));
        txtAjuda.setBorder(null);
        txtAjuda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAjuda.setForeground(new java.awt.Color(0, 209, 30));
        txtAjuda.setText("O tamanho que cada bot (cobra) terá no início do jogo. Essa medida pode influenciar diretamente na facilidade ou dificuldade de adquirir as frutas, principalmente as primeiras");
        jScrollPane3.setViewportView(txtAjuda);

        paneConfig.add(jScrollPane3);
        jScrollPane3.setBounds(10, 50, 480, 90);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 209, 30));
        jLabel6.setText("Tempo Limite do Jogo");
        paneConfig.add(jLabel6);
        jLabel6.setBounds(150, 290, 220, 40);

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setBorder(null);

        txtAjuda3.setEditable(false);
        txtAjuda3.setBackground(new java.awt.Color(255, 255, 255));
        txtAjuda3.setBorder(null);
        txtAjuda3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAjuda3.setForeground(new java.awt.Color(0, 209, 30));
        txtAjuda3.setText("O tempo (em segundos) que o jogo terá, essa medida busca trazer controle do executor para não termos jogos extremamente longos.");
        jScrollPane4.setViewportView(txtAjuda3);

        paneConfig.add(jScrollPane4);
        jScrollPane4.setBounds(10, 330, 480, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(paneConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(paneConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel paneConfig;
    private javax.swing.JTextPane txtAjuda;
    private javax.swing.JTextPane txtAjuda2;
    private javax.swing.JTextPane txtAjuda3;
    // End of variables declaration//GEN-END:variables
}
